---
title: "Kursusintroduktion"
subtitle: "Finansiering — Fixed Income, Risiko & Regulering"
author: "Niklas Lehmann Jensen"

format:
  revealjs:
    width: 1150
    slide-number: true
    incremental: true
    logo: ../../themes/favicon.ico
    footer: "Finansiering — Kursusintroduktion"
    footer-logo-link: "#"
    theme: ../../themes/slides_themes.scss  # filsti m. "/"
    toc: true
    toc-depth: 2
    toc-title: Indhold
    transition: convex
    transition-speed: fast
    include-in-header:                                  # SAMLET ét sted
      - text: |
          <meta name="description" content="Kursusintroduktion til Finansiering (fixed income, renterisiko, realkredit, performanceattribution og regulering)."/>
      

slide-level: 4
title-slide-attributes:
  data-background-color: "#045D5D"
  data-footer: " "

# Fjern eller peg korrekt på filteret. Hvis du IKKE har lua-filen, så kommentér ud:
# filters:
#   - ../.. /filters/reveal-header.lua

# Slå fra under udvikling (kan sættes til true til sidst for one-file HTML)
embed-resources: false
#include-in-header: ../../themes/mathjax.html 
highlight-style: tango
open-graph:
  description: "Kursusintroduktion til Finansiering (fixed income, renterisiko, realkredit, performanceattribution og regulering)."
---

## Indhold og motivation {background="#00100F"}

#### Om mig (part 1)
- cand.oecon fra Aarhus Universitet i 2021
- Arbejdserfaring:
  - Studentermedhjælper og portefølje-analytiker i Sydbanks kapitalforvaltning (2018-2022)
  - Analytiker i Sydbanks afdeling for risikomodeller (2022-2023)
  - Senior analytiker i Scanrate (2023-)
  - Lektor i matematik og makroøkonomi på SDU (2022-2024)
  - Lektor i finansiering på AU (2024-)

#### Om mig (part 2)
- Fokus: fixed income, realkredit, finansiel matematik, programmering..
- Email: <p style="font-family: 'Courier New', Courier, monospace;">nlj@econ.au.dk</p>
- "Kontor" & træffetider: I er velkommen til at skrive en mail 24/7


### Kurset: Fra grundlæggende teori til praksis {background="#43464B"}

#### Hvilke kompetencer forventer jeg fra jer? 
- Matematik B 
- Grundlæggende forståelse for samfundsøkonomi 
- Evnen til at fordybe sig i pensum (surpirse)

#### Hvad er fokus i **Finansiering** (min del)?
- Fastforrentede obligationer & rentestruktur  
- Renterisiko (varighed/konveksitet, nøglerenter)  
- Dansk realkredit (match-funding, konvertering, CPR)  
- Prisfastsættelse af obligationer
- Performance: afkastopgørelse & dekomponering
- Regulering & case-studies (finanskrisen mm.)

#### Hovedblokke

1. **Renter & obligationer**  
2. **Rentestruktur & arbitrage**  
3. **Renterisiko** (varighed, konveksitet, delta-vektorer)  
4. **Dansk realkredit** (marked, lovgivning, produkter, konvertering)  
5. **Prisfastsættelse & OAS**  
6. **Performanceevaluering** (HPR, dekomponering)  
7. **Regulering & kriser** (før/efter 2008, SVB-case, “kan det ske igen?”)

. . .

...Når vi det hele??

#### Vil du synes denne del af faget er fedt?

Ja, hvis du…  

 - en gang **selv skal købe** en bolig og finansiere det igennem realkreditmarkedet
 - ønsker at forstå de risici investorer og boligejere står over for, når man er i det danske boligmarked
 - vil forstå, hvordan ændringer i økonomien kan påvirke prisen **på dit lån** igennem renten
 - hvorfor finanskrisen i 2008 skete, og hvilke eftervirkninger det har bragt med sig i form af regulering 
 - gerne vil have et indblik i **et af de sværeste** finansielle instrumenter at prise! 

## Lidt praktisk om kurset {background="#00100F"}

### Lokale/tider/format & eksamen {background="#43464B"}

#### Mødetider
- Forelæsninger: **tirsdag kl 08:15 til 10:00 og torsdag 14:15 til 16:00**  
- Øvelser: **sammen med Henning og Visti**
<div style="border: 2px solid #ccc; padding: 9px; border-radius: 15px; margin-bottom: 10px;">
Ændringer annonceres på Brightspace og i timen
</div>

#### Format
- Forelæsninger består af intuitiv gennemgang af pensum med **blandede** teoretiske og praktiske eksempler  
- Nogle gange vil der vises opgaver med Excel + Excel med solveropgaver - **forventes også i kan til eksamen og opgavesættene!**
- Aktiv deltagelse anbefales (spørg i timen, før/efter, eller over mail)

#### Bedømmelse
<div style="border: 2px solid #ccc; padding: 9px; border-radius: 15px; margin-bottom: 10px;">
Skriftlig eksamen (format & hjælpemidler: 4 timer, med hjælpemidler, dog ikke internet (.. og jeg jagter jer i efterlivet, hvis i bruger AI!))
</div>
- Dato: annonceres af eksamenskontoret  
- Forberedelse: forelæsninger, øvelser, opgavesæt og noter

### Kursusmaterialer {background="#43464B"}

#### Det primære pensum
- **Lektionsnoter i finansiering (2025)** — mit eget hjemmelavet kursuskompendium med fokus på de forrige nævnte emner. 
- **Fundamentals of Corporate Finance af Berk, DeMarzo og Harfor** — primært til 1 del. Der kan findes lidt om renter og obligationer


. . .

**Supplerende bøger for absurde tryhards** 

- Tanggaard, *Finansielle instrumenter og deres markeder*  
- Just Andresen, *Finansiel risikostyring*  
- Christensen, *Obligationsinvestering: Teori og praktisk anvendelse* 
- Rom, *Callable Mortgage Bonds*

#### Smagsprøve på centrale formler
- Pris (kupon): $P = \sum_{t=1}^{N} \frac{C}{(1+y)^t} + \frac{FV}{(1+y)^N}$

<br>

- Kronevarigheden: $(d) = \frac{D}{1+r}\cdot \frac{\text{Kurs}}{100} = MD \cdot \frac{\text{Kurs}}{100}$

<br>

- Kronekonveksitet: $(C) = \frac{\sum_{t=1}^{N} (t^2+t) c_t (1+r)^t}{(1+r)^2} \cdot 0.01^2$

<br>

- Gevinstkrav: $Gain = \frac{PV_{continue}-100\cdot(1+cost)}{PV_{continue}}\label{eq:kap6_RK_GainFormula2}$


### Hvordan er min del til eksamen? {background="#43464B"}

#### Eksamensstruktur
- Opgaver der rører dit og dat fra min del.. Så vidt muligt
- Min del af faget er ret ungt, jeg kan sagtens finde på at ændre strukturen og måden at stille spørgsmål på i år relativ til sidste år. (Samme forventninger!)
- I får en ny og mock-eksamen sammen med det gamle eksamenset (i har fået ordinær - i vil også få re-eksamen). Meget repræsentativ for i år også. Men jeg kan altid få gode nye ideér :-) 

. . .

Fokus på intuition! Men i *skal* også kunne regne. Jeg er dog en pragmatiker! 

