project:
  type: website
  output-dir: ../docs            # build into /docs at repo root
  resources:
    - themes/                    # ensure custom themes get published
    - Lektionsnote/Lektionsnoter_2025.pdf
    - exercises/Del2_OS2.pdf
    - slides/**/*

html-math-method: mathjax

execute:
  freeze: auto

website:
  title: "Finansiering 2025"
  site-url: https://lehfinancier.github.io/Finansiering2025/
  repo-url: https://github.com/Lehfinancier/Finansiering2025
  repo-subdir: "src"
  sidebar:
    title: "Finansiering"
    style: docked
    search: true
    tools:
      - icon: github
        href: https://github.com/Lehfinancier
      - icon: linkedin
        href: https://www.linkedin.com/in/niklas-lehmann-jensen-204088112
      - icon: twitter
        href: https://twitter.com/NiklasLehmann8
      - icon: snapchat
        href: https://i.imgflip.com/120j0e.jpg
      - icon: envelope
        href: mailto:nlj@econ.au.dk
    contents:
      - index.qmd
      - section: "Lektionsnoten"
        contents:
          - text: "Lektionsnote (PDF)"
            href: Lektionsnote/Lektionsnoter_2025.pdf
            target: _blank
      - section: "Lectures"
        contents:
          - slides/organizational/intro.qmd
          - slides/Rentedannelse/rentedannelsen.qmd
          - slides/Obligationsmarkedet/obligationsmarked.qmd
          - slides/Rentestrukturen/Rentestrukturen.qmd
          - slides/Risikomål/risikomaal.qmd
          - slides/Realkredit/realkredit.qmd
          - slides/Konverteringsmodel/konverteringsmodel.qmd
          - slides/PrisNoegletal/pricingkeyfigures.qmd
          - slides/FinanskrisenRegulering/financialcrisis.qmd
          - slides/PengeinstitutterRisikostyring/bankingandrisk.qmd
      - section: "Øvelsesopgaver"
        contents:
          - text: "Del 2 — OS2 (PDF)"
            href: exercises/Del2_OS2.pdf
            target: _blank

format:
  html:
    include-in-header: themes/mathjax.html
    theme:
      light: [themes/ws_light.scss, themes/block.scss]
      dark:  [themes/ws_dark.scss,  themes/block.scss]
    page-navigation: true
    embed-resources: true            # <- VIGTIGT: indlejr CSS/JS/ikoner i HTML  
  revealjs:
    include-in-header: themes/mathjax.html
    logo: themes/favicon.ico                # global logo for slides
    theme: themes/slides_themes.scss        # global slides theme
    slide-number: true
    incremental: true
    toc: true
    toc-depth: 2
    transition: convex
    transition-speed: fast
    embed-resources: true            # <- også for slides, så tema/logo virker live  

bibliography: eco.bib
