project:
  type: website
  output-dir:  ../docs/

html-math-method: mathjax

execute:
  freeze: auto

website:
  title: "Finansiering 2025"
  site-url: https://lehfinancier.github.io/Finansiering2025/
  repo-url: https://github.com/Lehfinancier/Finansiering2025
  repo-subdir: "src"
  repo-actions: [edit, issue]
  sidebar:
    style: floating
    search: true
    contents:
      - src/index.qmd
      - section: "Lectures"
        contents:
          - src/slides/organizational/intro.qmd
      - section: "Exercises"
        contents:
          - src/exercises/ex01.qmd
      - section: "Course Info"
        contents:
          - src/syllabus.qmd

format:
  html:
    include-in-header: ../themes/mathjax.html
    theme:
      light: [themes/ws_light.scss, themes/block.scss]
      dark:  [themes/ws_dark.scss, themes/block.scss]

  revealjs:
    include-in-header: themes/mathjax.html
    slide-number: true
    incremental: true
    toc: true
    toc-depth: 2
    transition: convex
    transition-speed: fast

bibliography: eco.bib

